//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace NProject.Models.Domain
{
    public partial class Meeting
    {
        public Meeting()
        {
            this.Participants = new HashSet<User>();
            this.MeetingComments = new HashSet<MeetingComment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.Guid AccessToken { get; set; }
    
        public virtual User Organizer { get; set; }
        public virtual ICollection<User> Participants { get; set; }
        public virtual ICollection<MeetingComment> MeetingComments { get; set; }
    }
    
}
