//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace NProject.Models.Domain
{
    public partial class MeetingComment
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual User Author { get; set; }
        public virtual Meeting Meeting { get; set; }
    }
    
}
