//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NProject.Models.Domain
{
    public partial class Project
    {
        public Project()
        {
            CreationDate = DateTime.UtcNow;
            this.Tasks = new HashSet<Task>();
            this.Invitations = new HashSet<Invitation>();
            this.Team = new HashSet<TeamMate>();
        }
        
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime? EndDate { get; set; }
        public decimal? Budget { get; set; }
    
        public virtual Workspace Workspace { get; set; }
        public virtual User ProjectManager { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<TeamMate> Team { get; set; }

        #region CostType

        [Column("CostType")]
        [Obsolete("Is used only by EF. Use CostType instead of")]
        public byte CostTypeValue { get; set; }

        [NotMapped]
        public CostType CostType
        {
#pragma warning disable 612,618
            get { return (CostType)CostTypeValue; }
            set { CostTypeValue = (byte)value; }
#pragma warning restore 612,618
        }

        #endregion
    }
    
}
