//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NProject.Models.Domain
{
    public enum AccessLevel
    {
        Full = 1,
        Partial = 2
    }

    public partial class TeamMate
    {
        [Key, Column(Order = 0)]
        public int UserId { get; set; }

        [Key, Column(Order = 1)]
        public int ProjectId { get; set; }

        public virtual User User { get; set; }

        public virtual Project Project { get; set; }

        [Column("AccessLevel")]
        public byte AccessLevelValue { get; set; }

        [NotMapped]
        public AccessLevel AccessLevel
        {
            get { return (AccessLevel) AccessLevelValue; }
            set { AccessLevelValue = (byte) value; }
        }
    }

}
