//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NProject.Models.Domain
{
    public partial class Workspace
    {
        public Workspace()
        {
            this.Projects = new HashSet<Project>();
            CreationDate = DateTime.UtcNow;
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual User Owner { get; set; }
    }
    
}
